# ecommerce_dbt:
#   outputs:
#     trino:
#       type: trino
#       method: none
#       user: admin
#       database: iceberg
#       host: trino-coordinator
#       port: 8080
#       schema: bronze
#       threads: 3
#     target: trion  

ecommerce_trino:
  target: dev

  outputs:
    dev:
      type: trino
      method: none
      user: trino
      host: trino-coordinator
      port: 8080
      database: iceberg
      schema: bronze
      threads: 4